[colors]
background = '#1e100b'
foreground = '#f9ddd3'

cursor_bg = '#ffb59b'
cursor_fg = '#1e100b'
cursor_border = '#ffb59b'

selection_bg = '#812900'
selection_fg = '#f9ddd3'

ansi = ['#1e100b', '#e14982', '#9ad66e', '#dbab7b', '#c06c4e', '#bf9283', '#ffb59b', '#abb2bf']
brights = ['#5c6370', '#e05f93', '#ace086', '#e8bf97', '#ffc2a6', '#b95f56', '#9d6f54', '#ffffff']
