[colors]
background = '#16161e'
foreground = '#73daca'

cursor_bg = '#7aa2f7'
cursor_fg = '#16161e'
cursor_border = '#7aa2f7'

selection_bg = '#7dcfff'
selection_fg = '#73daca'

ansi = ['#1a1b26', '#e94f48', '#6fd66e', '#dbd27b', '#6180e1', '#6e86b9', '#7aa2f7', '#abb2bf']
brights = ['#5c6370', '#e0605f', '#87e086', '#e8e097', '#b7d3ff', '#527fb1', '#6e79bb', '#ffffff']
